version: '3.4'

services: 
  ravendb:
    image: ravendb/ravendb

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0

  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch