version: '3.4'

services: 
  ravendb:
    environment:
      - RAVEN_Setup_Mode=None
      - RAVEN_Security_UnsecuredAccessAllowed='PrivateNetwork'
      - RAVEN_License_Eula_Accepted=true
    ports:
      - "8000:8080"